apiVersion: v1
kind: Namespace
metadata:
  name: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    shared-gateway-access: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbitorrent-pv-nfs-config
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    app.kubernetes.io/component: config
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/hdd2T/qbitorrent/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbitorrent-pv-nfs-download
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    app.kubernetes.io/component: downloads
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/hdd2T/qbitorrent/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-pvc-config
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    app.kubernetes.io/component: config
spec:
  storageClassName: ""
  volumeName: qbitorrent-pv-nfs-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-pvc-download
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    app.kubernetes.io/component: downloads
spec:
  storageClassName: ""
  volumeName: qbitorrent-pv-nfs-download
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitorrent
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbitorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbitorrent
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbitorrent-pvc-config
        - name: downloads
          persistentVolumeClaim:
            claimName: qbitorrent-pvc-download
      containers:
        - name: qbitorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: WEBUI_PORT
              value: "8090"
            - name: TORRENTING_PORT
              value: "6881"
            - name: TZ
              value: US/Eastern
          ports:
            - containerPort: 8090
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
            - containerPort: 6881
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: qbitorrent
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
  annotations:
    metallb.universe.tf/allow-shared-ip: qbitorrent
spec:
  selector:
    app.kubernetes.io/name: qbitorrent
  ports:
    - port: 8090
      name: webui
      targetPort: 8090
      protocol: TCP
    - port: 6881
      name: torrent-udp
      targetPort: 6881
      protocol: UDP
    - port: 6881
      name: torrent-tcp
      targetPort: 6881
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: qbitorrent
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "qbitorrent.snoozyhomelab.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: qbitorrent
          kind: Service
          namespace: qbitorrent
          port: 8090
