apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitorrent
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbitorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbitorrent
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbitorrent-pvc-config
        - name: downloads
          persistentVolumeClaim:
            claimName: qbitorrent-pvc-download
      containers:
        - name: qbitorrent
          image: lscr.io/linuxserver/qbittorrent:4.6.6
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qbitorrent-config
          ports:
            - containerPort: 8090
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
            - containerPort: 6881
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: qbitorrent
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
  annotations:
    metallb.universe.tf/allow-shared-ip: qbitorrent
spec:
  selector:
    app.kubernetes.io/name: qbitorrent
  ports:
    - port: 8090
      name: webui
      targetPort: 8090
      protocol: TCP
    - port: 6881
      name: torrent-udp
      targetPort: 6881
      protocol: UDP
    - port: 6881
      name: torrent-tcp
      targetPort: 6881
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: qbitorrent
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "qbitorrent.snoozyhomelab.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: qbitorrent
          kind: Service
          namespace: qbitorrent
          port: 8090
