apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: homelab-qbitorrent
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./qbitorrent/config
        containerPath: /mnt/hdd2T/qbitorrent/config
      - hostPath: ./qbitorrent/downloads
        containerPath: /mnt/hdd2T/qbitorrent/downloads
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP