apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-pvc-config
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    app.kubernetes.io/component: config
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-pvc-download
  namespace: qbitorrent
  labels:
    app.kubernetes.io/name: qbitorrent
    app.kubernetes.io/component: downloads
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi