services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8096
      - TORRENTING_PORT=6881
    volumes:
      # - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8096:8096
      - 6881:6881
      - 6881:6881/udp
    restart: always